const REACT_APP_GOOGLE_MAPS_KEY = "AIzaSyAeL-IBthXc4bDAIWz5BUSnuj4Kvr3A-w4";
export {REACT_APP_GOOGLE_MAPS_KEY};


// export const REACT_APP_GOOGLE_MAPS_KEY = "AIzaSyAeL-IBthXc4bDAIWz5BUSnuj4Kvr3A-w4";
  