const REACT_APP_GOOGLE_MAPS_KEY = "AIzaSyC5nKn2X9S8tR0cmYKyiXeOUXut5jEif6E";
export {REACT_APP_GOOGLE_MAPS_KEY};


// export const REACT_APP_GOOGLE_MAPS_KEY = "AIzaSyAeL-IBthXc4bDAIWz5BUSnuj4Kvr3A-w4";
  